start python solution.py
start python solution.py
start python solution.py
start python solution.py
start python solution.py
start python solution.py
start python solution.py
start python solution.py
start python solution.py
start python solution.py
start python solution.py
start python solution.py
start python solution.py
start python solution.py
start python solution.py
